name: GoldySays
main: net.novauniverse.goldysays.GoldySays
description: Goldy Say's
version: 1.0
author: The Golden Pro
api-version: 1.13
depend: [NovaCore, NovaCoreGameEngine]
softdepend: [NovaGamesTarget]